import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from 'react';
import { ApiError, apiDownload, apiRequest, V1_ROOT, withCursor, type ApiResult } from './api';
import { CurrentAdministrativeAuthorityPage } from './CurrentAdministrativeAuthorityPage';

type Resource = Record<string, any>;
type Page = { items: Resource[]; nextCursor?: string | null };
type Values = Record<string, string | boolean>;
type Field = { name: string; label: string; type?: 'text' | 'number' | 'datetime-local' | 'textarea' | 'checkbox' | 'select'; options?: string[]; required?: boolean; help?: string; placeholder?: string };
type Action = { label: string; path: (id: string) => string; destructive?: boolean; requireEtag?: boolean; idempotent?: boolean; fields?: Field[]; body?: (values: Values) => unknown; download?: boolean };
type Spec = { eyebrow: string; title: string; description: string; list?: (cursor?: string | null) => string; detail: (id: string) => string; columns?: string[]; create?: { path: string; fields: Field[]; body: (values: Values) => unknown; warning?: string }; actions?: Action[] };

const redacted = /(secret|password|token|private|raw|configuration|referenceKey)/i;
const asText = (value: any) => value === null || value === undefined || value === '' ? '—' : typeof value === 'object' ? '[structured]' : String(value);
const nullable = (value: string | boolean | undefined) => String(value ?? '').trim() || null;
const iso = (value: string | boolean | undefined) => nullable(value) ? new Date(String(value)).toISOString() : null;
const csv = (value: string | boolean | undefined) => String(value ?? '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);

function ErrorState({ error }: { error: unknown }) {
  let title = 'Request failed'; let detail = error instanceof Error ? error.message : 'Unable to complete request.'; let correlation: string | null = null;
  if (error instanceof ApiError) {
    correlation = error.correlationId;
    if (error.status === 401) { title = 'Authentication required'; detail = 'A trusted control-plane session is required.'; }
    else if (error.status === 403) { title = 'Not authorized'; detail = 'Administrative Authorization denied this operation. Server authorization is final.'; }
    else if (error.status === 409) { title = 'Conflict'; }
    else if (error.status === 412) { title = 'Stale revision'; detail = 'Refresh and retry with the latest authoritative ETag.'; }
    else if (error.status === 503) { title = 'Required evaluator unavailable'; }
  }
  return <div className="state-card state-error" role="alert"><strong>{title}</strong><span>{detail}</span>{correlation ? <span className="mono subline">Correlation: {correlation}</span> : null}</div>;
}

function FieldControl({ field, value, onChange }: { field: Field; value?: string | boolean; onChange: (value: string | boolean) => void }) {
  if (field.type === 'checkbox') return <label className="check-field"><input type="checkbox" checked={Boolean(value)} onChange={(e) => onChange(e.target.checked)} /><span>{field.label}</span>{field.help ? <small>{field.help}</small> : null}</label>;
  if (field.type === 'select') return <label><span>{field.label}</span><select required={field.required} value={String(value ?? '')} onChange={(e) => onChange(e.target.value)}><option value="">Select…</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select>{field.help ? <small>{field.help}</small> : null}</label>;
  if (field.type === 'textarea') return <label><span>{field.label}</span><textarea required={field.required} value={String(value ?? '')} placeholder={field.placeholder} onChange={(e) => onChange(e.target.value)} />{field.help ? <small>{field.help}</small> : null}</label>;
  return <label><span>{field.label}</span><input type={field.type ?? 'text'} required={field.required} value={String(value ?? '')} placeholder={field.placeholder} onChange={(e) => onChange(e.target.value)} />{field.help ? <small>{field.help}</small> : null}</label>;
}

function Form({ fields, label, warning, onSubmit }: { fields: Field[]; label: string; warning?: string; onSubmit: (values: Values) => Promise<void> }) {
  const initial = useMemo(() => Object.fromEntries(fields.map((f) => [f.name, f.type === 'checkbox' ? false : ''])) as Values, [fields]);
  const [values, setValues] = useState<Values>(initial); const [pending, setPending] = useState(false); const [error, setError] = useState<unknown>(null);
  async function submit(e: FormEvent) { e.preventDefault(); if (warning && !window.confirm(warning)) return; setPending(true); setError(null); try { await onSubmit(values); setValues(initial); } catch (cause) { setError(cause); } finally { setPending(false); } }
  return <form className="semantic-form" onSubmit={(e) => void submit(e)}><div className="form-grid">{fields.map((field) => <FieldControl key={field.name} field={field} value={values[field.name]} onChange={(value) => setValues((current) => ({ ...current, [field.name]: value }))} />)}</div>{warning ? <p className="warning-copy">{warning}</p> : null}{error !== null ? <ErrorState error={error} /> : null}<button className="button" disabled={pending}>{pending ? 'Working…' : label}</button></form>;
}

function Details({ resource }: { resource: Resource }) {
  return <dl className="resource-details">{Object.entries(resource).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{redacted.test(key) ? 'Configured / redacted' : asText(value)}</dd></div>)}</dl>;
}

function Workspace({ spec }: { spec: Spec }) {
  const [pages, setPages] = useState<Page[]>([]); const [loading, setLoading] = useState(Boolean(spec.list)); const [error, setError] = useState<unknown>(null); const [refresh, setRefresh] = useState(0);
  const [id, setId] = useState(''); const [detail, setDetail] = useState<ApiResult<Resource> | null>(null); const [actionValues, setActionValues] = useState<Values>({}); const [pendingAction, setPendingAction] = useState('');
  const items = pages.flatMap((page) => page.items); const next = pages.at(-1)?.nextCursor ?? null;

  useEffect(() => {
    if (!spec.list) return;
    const controller = new AbortController(); setLoading(true); setError(null); setPages([]);
    apiRequest<Page>(spec.list(null), { signal: controller.signal }).then(({ data }) => setPages([data])).catch((cause) => { if (!(cause instanceof DOMException && cause.name === 'AbortError')) setError(cause); }).finally(() => setLoading(false));
    return () => controller.abort();
  }, [refresh, spec.list]);

  async function lookup(target = id) { if (!target) return; setError(null); try { setDetail(await apiRequest<Resource>(spec.detail(target))); setId(target); } catch (cause) { setError(cause); setDetail(null); } }
  async function loadMore() { if (!spec.list || !next) return; setLoading(true); try { const { data } = await apiRequest<Page>(spec.list(next)); setPages((current) => [...current, data]); } catch (cause) { setError(cause); } finally { setLoading(false); } }
  async function create(values: Values) { if (!spec.create) return; const result = await apiRequest<Resource>(spec.create.path, { method: 'POST', idempotent: true, body: spec.create.body(values) }); const createdId = result.data?.id; if (typeof createdId === 'string') { setId(createdId); setDetail(result); } setRefresh((v) => v + 1); }
  async function act(action: Action) {
    if (!id || !detail) return; if (action.destructive && !window.confirm(`${action.label} changes authoritative state. Confirm.`)) return;
    setPendingAction(action.label); setError(null);
    try {
      if (action.download) {
        const blob = await apiDownload(action.path(id), { method: 'POST' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `wyrmgate-audit-export-${id}.ndjson`; anchor.click(); URL.revokeObjectURL(url);
      } else {
        const result = await apiRequest<Resource>(action.path(id), { method: 'POST', idempotent: action.idempotent !== false, etag: action.requireEtag === false ? undefined : detail.etag ?? undefined, body: action.body ? action.body(actionValues) : undefined });
        setDetail(result); setRefresh((v) => v + 1);
      }
      setActionValues({});
    } catch (cause) { setError(cause); } finally { setPendingAction(''); }
  }

  return <section className="page-stack"><header className="page-header"><p className="eyebrow">{spec.eyebrow}</p><h1>{spec.title}</h1><p>{spec.description}</p></header>
    {spec.create ? <details className="card expandable"><summary>Create</summary><Form fields={spec.create.fields} label="Create" warning={spec.create.warning} onSubmit={create} /></details> : null}
    {error !== null ? <ErrorState error={error} /> : null}
    {spec.list ? <>{loading && items.length === 0 ? <div className="state-card">Loading…</div> : null}{!loading && items.length === 0 && error === null ? <div className="state-card">No resources found.</div> : null}{items.length > 0 ? <div className="table-wrap"><table><thead><tr>{(spec.columns ?? ['id']).map((column) => <th key={column}>{column}</th>)}<th>Open</th></tr></thead><tbody>{items.map((item, index) => <tr key={String(item.id ?? index)}>{(spec.columns ?? ['id']).map((column) => <td key={column}>{redacted.test(column) ? 'Redacted' : asText(item[column])}</td>)}<td>{typeof item.id === 'string' ? <button className="text-button" onClick={() => void lookup(item.id)}>View</button> : null}</td></tr>)}</tbody></table></div> : null}{next ? <button className="button secondary" onClick={() => void loadMore()}>Load more</button> : null}</> : null}
    <div className="card lookup-card"><label><span>Resource ID</span><input value={id} onChange={(e) => setId(e.target.value)} /></label><button className="button secondary" disabled={!id} onClick={() => void lookup()}>Lookup</button></div>
    {detail ? <section className="card detail-panel"><Details resource={detail.data} />{spec.actions?.map((action) => <div className="action-block" key={action.label}>{action.fields?.map((field) => <FieldControl key={field.name} field={field} value={actionValues[field.name]} onChange={(value) => setActionValues((current) => ({ ...current, [field.name]: value }))} />)}<button className={action.destructive ? 'button danger' : 'button secondary'} disabled={Boolean(pendingAction)} onClick={() => void act(action)}>{pendingAction === action.label ? 'Working…' : action.label}</button></div>)}</section> : null}
  </section>;
}

function Tabs({ tabs }: { tabs: Array<{ id: string; label: string; content: ReactNode }> }) { const [active, setActive] = useState(tabs[0]?.id ?? ''); const current = tabs.find((tab) => tab.id === active) ?? tabs[0]; return <><div className="tabs">{tabs.map((tab) => <button key={tab.id} className={active === tab.id ? 'active' : ''} onClick={() => setActive(tab.id)}>{tab.label}</button>)}</div>{current?.content}</>; }
const list = (path: string, extra?: Record<string, string | undefined>) => (cursor?: string | null) => withCursor(path, cursor, extra);
const scopeFields: Field[] = [{ name: 'scopeType', label: 'Scope type', type: 'select', options: ['GLOBAL', 'ORGANIZATION', 'APPLICATION', 'APPLICATION_TARGET', 'SOURCE_SYSTEM', 'CONNECTOR_INSTANCE', 'IDENTITY_POPULATION', 'CANONICAL_ATTRIBUTE_CLASSIFICATION', 'SPECIFIC_RESOURCE'], required: true }, { name: 'scopeResourceType', label: 'Resource type' }, { name: 'scopeResourceId', label: 'Resource ID' }, { name: 'scopeKey', label: 'Scope key' }];
const scope = (v: Values) => ({ type: v.scopeType, resourceType: nullable(v.scopeResourceType), resourceId: nullable(v.scopeResourceId), scopeKey: nullable(v.scopeKey) });

const principalSpec: Spec = { eyebrow: 'Identity', title: 'Principals', description: 'Technical account authority owned by Identity; provider observation is not Principal authority.', list: list(`${V1_ROOT}/principals`), detail: (id) => `${V1_ROOT}/principals/${encodeURIComponent(id)}`, columns: ['nativePrincipalKey', 'applicationTargetId', 'identityId', 'lifecycleState'], create: { path: `${V1_ROOT}/principals`, fields: [{ name: 'applicationTargetId', label: 'Application Target ID', required: true }, { name: 'nativePrincipalKey', label: 'Native principal key', required: true }], body: (v) => ({ applicationTargetId: v.applicationTargetId, nativePrincipalKey: v.nativePrincipalKey }) }, actions: [{ label: 'Correlate to Identity', path: (id) => `${V1_ROOT}/principals/${encodeURIComponent(id)}:correlate`, fields: [{ name: 'identityId', label: 'Identity ID', required: true }], body: (v) => ({ identityId: v.identityId }) }] };
const applicationSpec: Spec = { eyebrow: 'Catalog', title: 'Applications', description: 'Governed Application authority.', list: list(`${V1_ROOT}/applications`), detail: (id) => `${V1_ROOT}/applications/${encodeURIComponent(id)}`, columns: ['code', 'name', 'lifecycleState', 'revision'], create: { path: `${V1_ROOT}/applications`, fields: [{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }], body: (v) => ({ code: v.code, name: v.name }) }, actions: [{ label: 'Retire', path: (id) => `${V1_ROOT}/applications/${encodeURIComponent(id)}/retire`, destructive: true }] };
const roleSpec: Spec = { eyebrow: 'Catalog', title: 'Roles', description: 'Business/application Role authority; composition is versioned separately.', list: list(`${V1_ROOT}/roles`), detail: (id) => `${V1_ROOT}/roles/${encodeURIComponent(id)}`, columns: ['code', 'name', 'roleType', 'lifecycleState'], create: { path: `${V1_ROOT}/roles`, fields: [{ name: 'roleType', label: 'Role type', type: 'select', options: ['BUSINESS', 'APPLICATION'], required: true }, { name: 'applicationId', label: 'Application ID' }, { name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }], body: (v) => ({ roleType: v.roleType, applicationId: nullable(v.applicationId), code: v.code, name: v.name }) }, actions: [{ label: 'Retire', path: (id) => `${V1_ROOT}/roles/${encodeURIComponent(id)}/retire`, destructive: true }] };
const assignmentSpec: Spec = { eyebrow: 'Access', title: 'Access Assignments', description: 'Authoritative business access intent.', list: list(`${V1_ROOT}/access-assignments`), detail: (id) => `${V1_ROOT}/access-assignments/${encodeURIComponent(id)}`, columns: ['identityId', 'targetKind', 'lifecycleState', 'principalConstraintKind'], create: { path: `${V1_ROOT}/access-assignments`, fields: [{ name: 'identityId', label: 'Identity ID', required: true }, { name: 'targetKind', label: 'Target kind', type: 'select', options: ['ROLE', 'ENTITLEMENT'], required: true }, { name: 'roleId', label: 'Role ID' }, { name: 'entitlementId', label: 'Entitlement ID' }, { name: 'principalConstraintKind', label: 'Principal constraint', type: 'select', options: ['ANY', 'SPECIFIC'], required: true }, { name: 'specificPrincipalId', label: 'Specific Principal ID' }, { name: 'validFrom', label: 'Valid from', type: 'datetime-local' }, { name: 'validUntil', label: 'Valid until', type: 'datetime-local' }], body: (v) => ({ identityId: v.identityId, targetKind: v.targetKind, roleId: nullable(v.roleId), entitlementId: nullable(v.entitlementId), principalConstraintKind: v.principalConstraintKind, specificPrincipalId: nullable(v.specificPrincipalId), validFrom: iso(v.validFrom), validUntil: iso(v.validUntil) }) }, actions: ['suspend', 'resume', 'cancel', 'revoke'].map((name) => ({ label: name[0].toUpperCase() + name.slice(1), path: (id) => `${V1_ROOT}/access-assignments/${encodeURIComponent(id)}/${name}`, destructive: name === 'cancel' || name === 'revoke' })) };
const effectiveSpec: Spec = { eyebrow: 'Access · projection', title: 'Effective Access', description: 'Read-only entitlement-level projection, never editable business intent.', list: list(`${V1_ROOT}/effective-access`), detail: (id) => `${V1_ROOT}/effective-access/${encodeURIComponent(id)}`, columns: ['identityId', 'entitlementId', 'principalConstraintKey', 'supportCount'] };
const approvalSpec: Spec = { eyebrow: 'Governance', title: 'Approval Inbox', description: 'Current reusable approval work.', list: list(`${V1_ROOT}/governance/approval-inbox`), detail: (id) => `${V1_ROOT}/governance/approvals/${encodeURIComponent(id)}`, columns: ['subjectKind', 'subjectId', 'state', 'currentStageOrdinal'], actions: [{ label: 'Approve', path: (id) => `${V1_ROOT}/governance/approvals/${encodeURIComponent(id)}/approve`, fields: [{ name: 'reason', label: 'Reason', type: 'textarea' }], body: (v) => ({ reason: nullable(v.reason) }) }, { label: 'Reject', path: (id) => `${V1_ROOT}/governance/approvals/${encodeURIComponent(id)}/reject`, destructive: true, fields: [{ name: 'reason', label: 'Reason', type: 'textarea' }], body: (v) => ({ reason: nullable(v.reason) }) }] };
const campaignSpec: Spec = { eyebrow: 'Governance', title: 'Review Campaigns', description: 'Access certification campaign state, separate from remediation state.', list: list(`${V1_ROOT}/governance/review-campaigns`), detail: (id) => `${V1_ROOT}/governance/review-campaigns/${encodeURIComponent(id)}`, columns: ['subjectIdentityId', 'reviewerIdentityId', 'state', 'generatedItemCount'], create: { path: `${V1_ROOT}/governance/review-campaigns`, fields: [{ name: 'subjectIdentityId', label: 'Subject Identity ID', required: true }, { name: 'reviewerIdentityId', label: 'Reviewer Identity ID', required: true }, { name: 'snapshotAt', label: 'Snapshot at', type: 'datetime-local', required: true }], body: (v) => ({ subjectIdentityId: v.subjectIdentityId, reviewerIdentityId: v.reviewerIdentityId, snapshotAt: iso(v.snapshotAt) }) }, actions: [{ label: 'Start', path: (id) => `${V1_ROOT}/governance/review-campaigns/${encodeURIComponent(id)}/start` }] };
const reviewSpec: Spec = { eyebrow: 'Governance', title: 'Review Inbox', description: 'Current reviewer work; KEEP/REVOKE remain semantic decisions.', list: list(`${V1_ROOT}/governance/review-inbox`), detail: (id) => `${V1_ROOT}/governance/review-items/${encodeURIComponent(id)}`, columns: ['identityId', 'targetKind', 'state', 'decision'], actions: [{ label: 'Keep', path: (id) => `${V1_ROOT}/governance/review-items/${encodeURIComponent(id)}/keep`, fields: [{ name: 'reason', label: 'Reason', type: 'textarea' }], body: (v) => ({ reason: nullable(v.reason) }) }, { label: 'Revoke', path: (id) => `${V1_ROOT}/governance/review-items/${encodeURIComponent(id)}/revoke`, destructive: true, fields: [{ name: 'reason', label: 'Reason', type: 'textarea' }], body: (v) => ({ reason: nullable(v.reason) }) }] };
const adminRoleSpec: Spec = { eyebrow: 'Administration', title: 'Administrative Roles', description: 'Control-plane permission sets, distinct from Catalog Roles and token claims.', list: list(`${V1_ROOT}/administrative-roles`), detail: (id) => `${V1_ROOT}/administrative-roles/${encodeURIComponent(id)}`, columns: ['code', 'name', 'revision'], create: { path: `${V1_ROOT}/administrative-roles`, fields: [{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'permissions', label: 'Permissions', type: 'textarea', required: true }], body: (v) => ({ code: v.code, name: v.name, permissions: csv(v.permissions) }) }, actions: [{ label: 'Add permission', path: (id) => `${V1_ROOT}/administrative-roles/${encodeURIComponent(id)}:add-permission`, fields: [{ name: 'permission', label: 'Permission', required: true }], body: (v) => ({ permission: v.permission }) }, { label: 'Remove permission', path: (id) => `${V1_ROOT}/administrative-roles/${encodeURIComponent(id)}:remove-permission`, destructive: true, fields: [{ name: 'permission', label: 'Permission', required: true }], body: (v) => ({ permission: v.permission }) }] };

function ScopedCatalog({ kind }: { kind: 'targets' | 'entitlements' | 'versions' }) {
  const [parent, setParent] = useState(''); const [active, setActive] = useState('');
  const parentType = kind === 'versions' ? 'Role ID' : 'Application ID';
  if (!active) return <section className="page-stack"><header className="page-header"><p className="eyebrow">Catalog · scoped</p><h1>{kind === 'targets' ? 'Application Targets' : kind === 'entitlements' ? 'Entitlements' : 'Role Versions'}</h1></header><div className="card lookup-card"><label><span>{parentType}</span><input value={parent} onChange={(e) => setParent(e.target.value)} /></label><button className="button" disabled={!parent} onClick={() => setActive(parent)}>Open</button></div></section>;
  if (kind === 'targets') return <Workspace spec={{ eyebrow: 'Catalog', title: 'Application Targets', description: 'Technical targets belonging to one governed Application.', list: list(`${V1_ROOT}/applications/${encodeURIComponent(active)}/targets`), detail: (id) => `${V1_ROOT}/application-targets/${encodeURIComponent(id)}`, columns: ['code', 'lifecycleState', 'revision'], create: { path: `${V1_ROOT}/applications/${encodeURIComponent(active)}/targets`, fields: [{ name: 'code', label: 'Code', required: true }], body: (v) => ({ code: v.code }) }, actions: [{ label: 'Retire', path: (id) => `${V1_ROOT}/application-targets/${encodeURIComponent(id)}/retire`, destructive: true }] }} />;
  if (kind === 'entitlements') return <Workspace spec={{ eyebrow: 'Catalog', title: 'Entitlements', description: 'Governed Entitlement authority for one Application.', list: list(`${V1_ROOT}/applications/${encodeURIComponent(active)}/entitlements`), detail: (id) => `${V1_ROOT}/entitlements/${encodeURIComponent(id)}`, columns: ['code', 'entitlementType', 'lifecycleState'], create: { path: `${V1_ROOT}/applications/${encodeURIComponent(active)}/entitlements`, fields: [{ name: 'applicationTargetId', label: 'Application Target ID' }, { name: 'code', label: 'Code', required: true }, { name: 'nativeKey', label: 'Native key' }, { name: 'entitlementType', label: 'Entitlement type', required: true }], body: (v) => ({ applicationTargetId: nullable(v.applicationTargetId), code: v.code, nativeKey: nullable(v.nativeKey), entitlementType: v.entitlementType }) }, actions: [{ label: 'Retire', path: (id) => `${V1_ROOT}/entitlements/${encodeURIComponent(id)}/retire`, destructive: true }] }} />;
  return <Workspace spec={{ eyebrow: 'Catalog · composition', title: 'Role Versions', description: 'Typed immutable Role/Entitlement composition.', list: list(`${V1_ROOT}/roles/${encodeURIComponent(active)}/versions`), detail: (id) => `${V1_ROOT}/roles/${encodeURIComponent(active)}/versions/${encodeURIComponent(id)}`, columns: ['versionNumber', 'state', 'revision'], create: { path: `${V1_ROOT}/roles/${encodeURIComponent(active)}/versions`, fields: [{ name: 'members', label: 'Members', type: 'textarea', required: true, placeholder: 'ENTITLEMENT:<uuid>\nAPPLICATION_ROLE:<uuid>' }], body: (v) => ({ members: String(v.members).split(/\n/).map((line) => line.trim()).filter(Boolean).map((line) => { const [kindName, memberId] = line.split(':', 2); return kindName === 'ENTITLEMENT' ? { kind: 'ENTITLEMENT', entitlementId: memberId } : { kind: 'APPLICATION_ROLE', roleId: memberId }; }) }) }, actions: [{ label: 'Validate', path: (id) => `${V1_ROOT}/roles/${encodeURIComponent(active)}/versions/${encodeURIComponent(id)}/validate` }, { label: 'Activate', path: (id) => `${V1_ROOT}/roles/${encodeURIComponent(active)}/versions/${encodeURIComponent(id)}/activate` }] }} />;
}

function AccessRequestPage() { return <Workspace spec={{ eyebrow: 'Governance', title: 'Access Requests', description: 'Create/read/submit typed access requests.', detail: (id) => `${V1_ROOT}/governance/access-requests/${encodeURIComponent(id)}`, create: { path: `${V1_ROOT}/governance/access-requests`, fields: [{ name: 'beneficiaryIdentityId', label: 'Beneficiary Identity ID', required: true }, { name: 'targetKind', label: 'Target kind', type: 'select', options: ['ROLE', 'ENTITLEMENT'], required: true }, { name: 'targetId', label: 'Target ID', required: true }, { name: 'principalConstraintKind', label: 'Principal constraint', type: 'select', options: ['ANY', 'SPECIFIC'], required: true }, { name: 'specificPrincipalId', label: 'Specific Principal ID' }], body: (v) => ({ beneficiaryIdentityId: v.beneficiaryIdentityId, items: [{ targetKind: v.targetKind, targetId: v.targetId, principalConstraintKind: v.principalConstraintKind, specificPrincipalId: nullable(v.specificPrincipalId), validFrom: null, validUntil: null }] }) }, actions: [{ label: 'Submit', path: (id) => `${V1_ROOT}/governance/access-requests/${encodeURIComponent(id)}/submit` }] }} />; }
function SimpleGap({ title, issue, children }: { title: string; issue: number; children: ReactNode }) { return <section className="page-stack"><header className="page-header"><p className="eyebrow">Public API boundary</p><h1>{title}</h1><p>{children}</p></header><div className="state-card"><strong>Tracked as #{issue}</strong><span>The console leaves this surface unavailable rather than bypassing the owning capability.</span></div></section>; }

function CredentialPageInner() { const [principal, setPrincipal] = useState(''); const [active, setActive] = useState(''); if (!active) return <section className="page-stack"><header className="page-header"><p className="eyebrow">Credential</p><h1>Credentials</h1><p>Credential list is contractually scoped to one Principal.</p></header><div className="card lookup-card"><label><span>Principal ID</span><input value={principal} onChange={(e) => setPrincipal(e.target.value)} /></label><button className="button" disabled={!principal} onClick={() => setActive(principal)}>Open</button></div></section>;
  return <Workspace spec={{ eyebrow: 'Credential', title: 'Credentials', description: 'Metadata/control plane only; raw secret/private material must never enter this UI.', list: list(`${V1_ROOT}/credentials`, { principalId: active }), detail: (id) => `${V1_ROOT}/credentials/${encodeURIComponent(id)}`, columns: ['kind', 'lifecycleState', 'validFrom', 'validUntil'], create: { path: `${V1_ROOT}/credentials`, warning: 'Enter only an opaque external secret reference, never the secret/private material itself.', fields: [{ name: 'principalId', label: 'Principal ID', required: true }, { name: 'kind', label: 'Kind', type: 'select', options: ['PASSWORD', 'API_KEY', 'SSH_KEY', 'CERTIFICATE', 'OAUTH_CLIENT_SECRET'], required: true }, { name: 'providerType', label: 'Secret provider type', required: true }, { name: 'referenceKey', label: 'Opaque reference key', required: true }, { name: 'validFrom', label: 'Valid from', type: 'datetime-local' }, { name: 'validUntil', label: 'Valid until', type: 'datetime-local' }], body: (v) => ({ principalId: v.principalId, kind: v.kind, secretReference: { providerType: v.providerType, referenceKey: v.referenceKey }, validFrom: iso(v.validFrom), validUntil: iso(v.validUntil) }) }, actions: [{ label: 'Revoke', path: (id) => `${V1_ROOT}/credentials/${encodeURIComponent(id)}:revoke`, destructive: true }, { label: 'Compromise', path: (id) => `${V1_ROOT}/credentials/${encodeURIComponent(id)}:compromise`, destructive: true }, { label: 'Plan rotation', path: (id) => `${V1_ROOT}/credentials/${encodeURIComponent(id)}:rotate`, requireEtag: false }] }} />; }

function IntegrationPageInner() {
  const connector: Spec = { eyebrow: 'Integration', title: 'Connector Instances', description: 'Integration-owned connector lifecycle/configuration. Provider observation is not Catalog/Access authority.', detail: (id) => `${V1_ROOT}/connectors/${encodeURIComponent(id)}`, create: { path: `${V1_ROOT}/connectors`, fields: [{ name: 'connectorType', label: 'Connector type', required: true }, { name: 'runtimeId', label: 'Runtime ID', required: true }, { name: 'runtimeVersion', label: 'Runtime version', required: true }, { name: 'configurationVersion', label: 'Configuration version', type: 'number', required: true }, { name: 'configuration', label: 'Provider configuration JSON', type: 'textarea', required: true, help: 'Do not place secrets here.' }, { name: 'secretReference', label: 'Opaque secret reference' }], body: (v) => ({ connectorType: v.connectorType, runtimeId: v.runtimeId, runtimeVersion: v.runtimeVersion, configurationVersion: Number(v.configurationVersion), configuration: JSON.parse(String(v.configuration || '{}')), secretReference: nullable(v.secretReference) }) }, actions: [{ label: 'Disable', path: (id) => `${V1_ROOT}/connectors/${encodeURIComponent(id)}:disable`, destructive: true }] };
  return <Tabs tabs={[{ id: 'connector', label: 'Connectors', content: <Workspace spec={connector} /> }, { id: 'binding', label: 'Bindings', content: <Workspace spec={{ eyebrow: 'Integration', title: 'Connector Bindings', description: 'Public binding administration lookup. The current checked-in contract does not define a request schema for create/update, so the browser does not invent one.', detail: (id) => `${V1_ROOT}/connector-bindings/${encodeURIComponent(id)}`, actions: [{ label: 'Disable', path: (id) => `${V1_ROOT}/connector-bindings/${encodeURIComponent(id)}:disable`, destructive: true }] }} /> }, { id: 'worker', label: 'Workers', content: <Workspace spec={{ eyebrow: 'Integration', title: 'Connector Workers', description: 'Public registration lookup. Internal worker execution protocol is never exposed to the browser.', detail: (id) => `${V1_ROOT}/connector-workers/${encodeURIComponent(id)}`, actions: [{ label: 'Disable', path: (id) => `${V1_ROOT}/connector-workers/${encodeURIComponent(id)}:disable`, destructive: true }] }} /> }, { id: 'ops', label: 'Operations', content: <SimpleGap title="Provisioning & Reconciliation" issue={266}>No accepted public operator read API currently exposes provisioning/reconciliation process state; the internal worker protocol remains private.</SimpleGap> }]} />;
}

function adminSpec(kind: 'grant' | 'delegation' | 'elevation' | 'break-glass'): Spec {
  if (kind === 'grant') return { eyebrow: 'Administration', title: 'Administrative Grants', description: 'Direct scoped authority.', list: list(`${V1_ROOT}/administrative-grants`), detail: (id) => `${V1_ROOT}/administrative-grants/${encodeURIComponent(id)}`, columns: ['beneficiaryIdentityId', 'roleId', 'state', 'validUntil'], create: { path: `${V1_ROOT}/administrative-grants`, fields: [{ name: 'beneficiaryIdentityId', label: 'Beneficiary Identity ID', required: true }, { name: 'roleId', label: 'Admin Role ID', required: true }, ...scopeFields, { name: 'validUntil', label: 'Valid until', type: 'datetime-local' }, { name: 'grantable', label: 'Grantable', type: 'checkbox' }, { name: 'delegable', label: 'Delegable', type: 'checkbox' }, { name: 'authorityBasisGrantId', label: 'Authority basis Grant ID', required: true }], body: (v) => ({ beneficiaryIdentityId: v.beneficiaryIdentityId, roleId: v.roleId, scope: scope(v), validFrom: null, validUntil: iso(v.validUntil), grantable: Boolean(v.grantable), delegable: Boolean(v.delegable), authorityBasisGrantId: v.authorityBasisGrantId }) }, actions: [{ label: 'Revoke', path: (id) => `${V1_ROOT}/administrative-grants/${encodeURIComponent(id)}:revoke`, destructive: true }] };
  if (kind === 'delegation') return { eyebrow: 'Administration', title: 'Administrative Delegations', description: 'Single-hop delegated authority.', list: list(`${V1_ROOT}/administrative-delegations`), detail: (id) => `${V1_ROOT}/administrative-delegations/${encodeURIComponent(id)}`, columns: ['delegateIdentityId', 'sourceGrantId', 'state', 'validUntil'], actions: [{ label: 'Revoke', path: (id) => `${V1_ROOT}/administrative-delegations/${encodeURIComponent(id)}:revoke`, destructive: true }] };
  if (kind === 'elevation') return { eyebrow: 'Administration', title: 'Administrative Elevations', description: 'Finite JIT authority; Governance approval is evidence, Administration owns authority.', list: list(`${V1_ROOT}/administrative-elevations`), detail: (id) => `${V1_ROOT}/administrative-elevations/${encodeURIComponent(id)}`, columns: ['beneficiaryIdentityId', 'roleId', 'state', 'validUntil'], actions: [{ label: 'Request approval', path: (id) => `${V1_ROOT}/administrative-elevations/${encodeURIComponent(id)}:request-approval` }, { label: 'Apply approval', path: (id) => `${V1_ROOT}/administrative-elevations/${encodeURIComponent(id)}:apply` }, { label: 'Cancel', path: (id) => `${V1_ROOT}/administrative-elevations/${encodeURIComponent(id)}:cancel`, destructive: true }, { label: 'Revoke', path: (id) => `${V1_ROOT}/administrative-elevations/${encodeURIComponent(id)}:revoke`, destructive: true }] };
  return { eyebrow: 'Administration · emergency', title: 'Break-glass Operations', description: 'Emergency authority remains distinct, finite and post-use reviewed.', list: list(`${V1_ROOT}/administrative-break-glass-operations`), detail: (id) => `${V1_ROOT}/administrative-break-glass-operations/${encodeURIComponent(id)}`, columns: ['beneficiaryIdentityId', 'roleId', 'state', 'validUntil'], actions: [{ label: 'Revoke', path: (id) => `${V1_ROOT}/administrative-break-glass-operations/${encodeURIComponent(id)}:revoke`, destructive: true }, { label: 'Complete review', path: (id) => `${V1_ROOT}/administrative-break-glass-operations/${encodeURIComponent(id)}:complete-review`, fields: [{ name: 'outcome', label: 'Outcome', type: 'select', options: ['APPROVED_USE', 'POLICY_CONCERN', 'INCIDENT_FOLLOW_UP_REQUIRED'], required: true }, { name: 'summary', label: 'Summary', type: 'textarea', required: true }], body: (v) => ({ outcome: v.outcome, summary: v.summary }) }] };
}

export function PrincipalsPage() { return <Workspace spec={principalSpec} />; }
export function CatalogPage() { return <Tabs tabs={[{ id: 'apps', label: 'Applications', content: <Workspace spec={applicationSpec} /> }, { id: 'targets', label: 'Targets', content: <ScopedCatalog kind="targets" /> }, { id: 'entitlements', label: 'Entitlements', content: <ScopedCatalog kind="entitlements" /> }, { id: 'roles', label: 'Roles', content: <Workspace spec={roleSpec} /> }, { id: 'versions', label: 'Role versions', content: <ScopedCatalog kind="versions" /> }]} />; }
export function AccessPage() { return <Tabs tabs={[{ id: 'intent', label: 'Assignments', content: <Workspace spec={assignmentSpec} /> }, { id: 'effective', label: 'Effective access', content: <Workspace spec={effectiveSpec} /> }, { id: 'policy', label: 'Lifecycle policy', content: <Workspace spec={{ eyebrow: 'Access · policy', title: 'Lifecycle Access Policy', description: 'Typed policy read/activation is available at the accepted semantic endpoint; generic expression editing is intentionally not provided.', detail: () => `${V1_ROOT}/lifecycle-access-policy` }} /> }]} />; }
export function RequestsPage() { return <Tabs tabs={[{ id: 'request', label: 'Access request', content: <AccessRequestPage /> }, { id: 'approval', label: 'Approvals', content: <Workspace spec={approvalSpec} /> }]} />; }
export function ReviewsPage() { return <Tabs tabs={[{ id: 'campaign', label: 'Campaigns', content: <Workspace spec={campaignSpec} /> }, { id: 'inbox', label: 'Review inbox', content: <Workspace spec={reviewSpec} /> }]} />; }
export function PoliciesPage() { return <Tabs tabs={[{ id: 'governance', label: 'ACCESS_REQUEST', content: <Workspace spec={{ eyebrow: 'Governance · policy', title: 'ACCESS_REQUEST Policy Versions', description: 'Lookup and explicit lifecycle transitions.', detail: (id) => `${V1_ROOT}/governance/policies/access-request/versions/${encodeURIComponent(id)}`, actions: [{ label: 'READY', path: (id) => `${V1_ROOT}/governance/policies/access-request/versions/${encodeURIComponent(id)}:ready` }, { label: 'Activate', path: (id) => `${V1_ROOT}/governance/policies/access-request/versions/${encodeURIComponent(id)}:activate` }, { label: 'Cancel', path: (id) => `${V1_ROOT}/governance/policies/access-request/versions/${encodeURIComponent(id)}:cancel`, destructive: true }] }} /> }, { id: 'exceptions', label: 'Exceptions', content: <Workspace spec={{ eyebrow: 'Governance', title: 'Governance Exceptions', description: 'Scoped/time-bound exception lookup and revocation.', detail: (id) => `${V1_ROOT}/governance/exceptions/${encodeURIComponent(id)}`, actions: [{ label: 'Revoke', path: (id) => `${V1_ROOT}/governance/exceptions/${encodeURIComponent(id)}:revoke`, destructive: true }] }} /> }, { id: 'source', label: 'Source policies', content: <Workspace spec={{ eyebrow: 'Identity · source policy', title: 'Source Policy Lookup', description: 'SourceSystem policy endpoints require a SourceSystem identifier. Use the exact resource path via the accepted public API; SourceSystem administration itself is not a public console surface.', detail: (id) => `${V1_ROOT}/source-systems/${encodeURIComponent(id)}/correlation-policy` }} /> }]} />; }
export function CredentialsPage() { return <CredentialPageInner />; }
export function IntegrationsPage() { return <IntegrationPageInner />; }
export function AdministrationPage() { return <Tabs tabs={[{ id: 'roles', label: 'Roles', content: <Workspace spec={adminRoleSpec} /> }, { id: 'grants', label: 'Grants', content: <Workspace spec={adminSpec('grant')} /> }, { id: 'delegations', label: 'Delegations', content: <Workspace spec={adminSpec('delegation')} /> }, { id: 'elevations', label: 'Elevations', content: <Workspace spec={adminSpec('elevation')} /> }, { id: 'breakglass', label: 'Break-glass', content: <Workspace spec={adminSpec('break-glass')} /> }, { id: 'authority', label: 'My authority', content: <CurrentAdministrativeAuthorityPage /> }]} />; }
export function AuditPage() { return <Tabs tabs={[{ id: 'records', label: 'Records', content: <Workspace spec={{ eyebrow: 'Audit', title: 'Audit Records', description: 'Append-only semantic business/security evidence, not generic logging.', list: list(`${V1_ROOT}/audit-records`), detail: (id) => `${V1_ROOT}/audit-records/${encodeURIComponent(id)}`, columns: ['occurredAt', 'actionType', 'resourceType', 'outcome', 'actorId'] }} /> }, { id: 'exports', label: 'Exports', content: <Workspace spec={{ eyebrow: 'Audit', title: 'Audit Exports', description: 'Durable snapshot-frozen exports with re-authorization at download.', detail: (id) => `${V1_ROOT}/audit-exports/${encodeURIComponent(id)}`, actions: [{ label: 'Download NDJSON', path: (id) => `${V1_ROOT}/audit-exports/${encodeURIComponent(id)}:download`, download: true, requireEtag: false, idempotent: false }] }} /> }, { id: 'evidence', label: 'Evidence', content: <Workspace spec={{ eyebrow: 'Audit', title: 'Evidence Snapshots', description: 'Immutable evidence snapshots.', list: list(`${V1_ROOT}/evidence-snapshots`), detail: (id) => `${V1_ROOT}/evidence-snapshots/${encodeURIComponent(id)}`, columns: ['snapshotType', 'subjectResourceType', 'subjectResourceId', 'createdAt'] }} /> }, { id: 'holds', label: 'Legal hold', content: <Workspace spec={{ eyebrow: 'Audit · evidence lifecycle', title: 'Legal Holds', description: 'Governed evidence retention hold.', detail: (id) => `${V1_ROOT}/audit-evidence-lifecycle/legal-holds/${encodeURIComponent(id)}`, actions: [{ label: 'Release', path: (id) => `${V1_ROOT}/audit-evidence-lifecycle/legal-holds/${encodeURIComponent(id)}:release`, destructive: true, idempotent: false }] }} /> }, { id: 'purges', label: 'Purge', content: <Workspace spec={{ eyebrow: 'Audit · destructive evidence', title: 'Purge Operations', description: 'Dual-control destructive evidence operation.', detail: (id) => `${V1_ROOT}/audit-evidence-lifecycle/purges/${encodeURIComponent(id)}`, actions: [{ label: 'Approve purge', path: (id) => `${V1_ROOT}/audit-evidence-lifecycle/purges/${encodeURIComponent(id)}:approve`, destructive: true, idempotent: false }] }} /> }]} />; }
