import { type FormEvent, type ReactNode, useState } from 'react';
import { apiDownload, apiRequest, V1_ROOT, withCursor } from './api';
import {
  AccessPage as BaseAccessPage,
  AdministrationPage as BaseAdministrationPage,
  AuditPage as BaseAuditPage,
  CredentialsPage as BaseCredentialsPage,
  IntegrationsPage as BaseIntegrationsPage,
  PoliciesPage as BasePoliciesPage,
} from './ControlPlanePages';

type Values = Record<string, string>;
type Resource = Record<string, any>;
type Field = { name: string; label: string; type?: 'text' | 'textarea' | 'datetime-local' | 'select'; options?: string[]; required?: boolean; help?: string };

const nullable = (value?: string) => value?.trim() ? value.trim() : null;
const iso = (value?: string) => nullable(value) ? new Date(value!).toISOString() : null;
const csv = (value?: string) => (value ?? '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);

function Form({ fields, label, warning, onSubmit }: { fields: Field[]; label: string; warning?: string; onSubmit: (values: Values) => Promise<void> }) {
  const [values, setValues] = useState<Values>({}); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); if (warning && !window.confirm(warning)) return; setPending(true); setMessage(''); try { await onSubmit(values); setValues({}); setMessage('Operation accepted.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Operation failed.'); } finally { setPending(false); } }
  return <form className="semantic-form" onSubmit={(event) => void submit(event)}><div className="form-grid">{fields.map((field) => <label key={field.name}><span>{field.label}</span>{field.type === 'textarea' ? <textarea required={field.required} value={values[field.name] ?? ''} onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.value }))} /> : field.type === 'select' ? <select required={field.required} value={values[field.name] ?? ''} onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.value }))}><option value="">Select…</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select> : <input type={field.type ?? 'text'} required={field.required} value={values[field.name] ?? ''} onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.value }))} />}{field.help ? <small>{field.help}</small> : null}</label>)}</div>{warning ? <p className="warning-copy">{warning}</p> : null}{message ? <div className="state-card">{message}</div> : null}<button className="button" disabled={pending}>{pending ? 'Working…' : label}</button></form>;
}

function Supplement({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <section className="page-stack completeness"><header className="page-header"><p className="eyebrow">Contract-complete operations</p><h2>{title}</h2><p>{description}</p></header>{children}</section>; }

function ScopeFields() { return null; }
const scopeFields: Field[] = [{ name: 'scopeType', label: 'Scope type', type: 'select', options: ['GLOBAL', 'ORGANIZATION', 'APPLICATION', 'APPLICATION_TARGET', 'SOURCE_SYSTEM', 'CONNECTOR_INSTANCE', 'IDENTITY_POPULATION', 'CANONICAL_ATTRIBUTE_CLASSIFICATION', 'SPECIFIC_RESOURCE'], required: true }, { name: 'scopeResourceType', label: 'Scope resource type' }, { name: 'scopeResourceId', label: 'Scope resource ID' }, { name: 'scopeKey', label: 'Scope key' }];
const scope = (v: Values) => ({ type: v.scopeType, resourceType: nullable(v.scopeResourceType), resourceId: nullable(v.scopeResourceId), scopeKey: nullable(v.scopeKey) });

function LifecyclePolicyActivation() {
  const fields: Field[] = [{ name: 'predicateKind', label: 'Predicate', type: 'select', options: ['ALWAYS','CANONICAL_STRING_EQUALS','CANONICAL_BOOLEAN_EQUALS','CANONICAL_INTEGER_EQUALS','CANONICAL_DECIMAL_EQUALS','CANONICAL_DATE_EQUALS','CANONICAL_DATETIME_EQUALS','CANONICAL_ENUM_EQUALS','CANONICAL_STRING_CONTAINS','CANONICAL_BOOLEAN_CONTAINS','CANONICAL_INTEGER_CONTAINS','CANONICAL_DECIMAL_CONTAINS','CANONICAL_DATE_CONTAINS','CANONICAL_DATETIME_CONTAINS','CANONICAL_ENUM_CONTAINS','CANONICAL_STRING_CONTAINS_ANY','CANONICAL_BOOLEAN_CONTAINS_ANY','CANONICAL_INTEGER_CONTAINS_ANY','CANONICAL_DECIMAL_CONTAINS_ANY','CANONICAL_DATE_CONTAINS_ANY','CANONICAL_DATETIME_CONTAINS_ANY','CANONICAL_ENUM_CONTAINS_ANY','CANONICAL_STRING_CONTAINS_ALL','CANONICAL_BOOLEAN_CONTAINS_ALL','CANONICAL_INTEGER_CONTAINS_ALL','CANONICAL_DECIMAL_CONTAINS_ALL','CANONICAL_DATE_CONTAINS_ALL','CANONICAL_DATETIME_CONTAINS_ALL','CANONICAL_ENUM_CONTAINS_ALL'], required: true }, { name: 'canonicalKey', label: 'Canonical key' }, { name: 'expectedType', label: 'Expected type', type: 'select', options: ['STRING','BOOLEAN','INTEGER','DECIMAL','DATE','DATETIME','ENUM'] }, { name: 'expectedValues', label: 'Expected value(s)', type: 'textarea', help: 'One value per line. Equals/CONTAINS use the first value; CONTAINS_ANY/ALL use the set.' }, { name: 'targetKind', label: 'Target kind', type: 'select', options: ['ROLE','ENTITLEMENT'], required: true }, { name: 'targetId', label: 'Target ID', required: true }];
  return <details className="card expandable"><summary>Activate lifecycle-access policy</summary><Form fields={fields} label="Activate policy" warning="Policy activation can increase authoritative access intent. Server-side governance evaluation remains final." onSubmit={async (v) => { const values = csv(v.expectedValues); const kind = v.predicateKind; const expectedType = v.expectedType; const rule: Resource = { ruleId: crypto.randomUUID(), predicateKind: kind, canonicalKey: kind === 'ALWAYS' ? null : nullable(v.canonicalKey), targetKind: v.targetKind, targetId: v.targetId, expectedSet: [] }; const first = values[0]; if (kind.includes('CONTAINS_ANY') || kind.includes('CONTAINS_ALL')) rule.expectedSet = values.map((value) => ({ type: expectedType, [`${expectedType === 'DATETIME' ? 'dateTime' : expectedType.toLowerCase()}Value`]: expectedType === 'BOOLEAN' ? value === 'true' : expectedType === 'INTEGER' ? Number(value) : value })); else { delete rule.expectedSet; if (expectedType === 'STRING') rule.expectedString = first ?? null; if (expectedType === 'BOOLEAN') rule.expectedBoolean = first === 'true'; if (expectedType === 'INTEGER') rule.expectedInteger = first ? Number(first) : null; if (expectedType === 'DECIMAL') rule.expectedDecimal = first ?? null; if (expectedType === 'DATE') rule.expectedDate = first ?? null; if (expectedType === 'DATETIME') rule.expectedDateTime = first ? new Date(first).toISOString() : null; if (expectedType === 'ENUM') rule.expectedEnum = first ?? null; } await apiRequest(`${V1_ROOT}/lifecycle-access-policy:activate`, { method: 'POST', idempotent: true, body: { rules: [rule] } }); }} /></details>;
}

function GovernanceCreates() {
  const policyFields: Field[] = [{ name: 'defaultDecision', label: 'Default decision', type: 'select', options: ['AUTHORIZE','REQUIRE_APPROVAL','DENY'], required: true }, { name: 'code', label: 'SoD rule code' }, { name: 'leftEntitlementId', label: 'Left Entitlement ID' }, { name: 'rightEntitlementId', label: 'Right Entitlement ID' }, { name: 'severity', label: 'Severity', type: 'select', options: ['LOW','MEDIUM','HIGH','CRITICAL'] }, { name: 'action', label: 'Rule action', type: 'select', options: ['REQUIRE_APPROVAL','DENY'] }, { name: 'decisionMode', label: 'Approval decision mode', type: 'select', options: ['ANY_ONE','ALL'] }, { name: 'approvers', label: 'Approver Identity IDs', type: 'textarea', help: 'One UUID per line; blank means no approval plan.' }];
  const exceptionFields: Field[] = [{ name: 'subjectIdentityId', label: 'Subject Identity ID', required: true }, { name: 'sodRuleId', label: 'SoD Rule ID', required: true }, { name: 'businessReason', label: 'Business reason', type: 'textarea', required: true }, { name: 'validFrom', label: 'Valid from', type: 'datetime-local', required: true }, { name: 'validUntil', label: 'Valid until', type: 'datetime-local', required: true }, { name: 'predecessorExceptionId', label: 'Predecessor Exception ID' }, { name: 'decisionMode', label: 'Approval decision mode', type: 'select', options: ['ANY_ONE','ALL'] }, { name: 'approvers', label: 'Approver Identity IDs', type: 'textarea' }];
  const approvalPlan = (v: Values) => csv(v.approvers).length ? { stages: [{ decisionMode: v.decisionMode || 'ANY_ONE', approverIdentityIds: csv(v.approvers) }] } : null;
  return <div className="card-grid"><details className="card expandable"><summary>Create ACCESS_REQUEST policy version</summary><Form fields={policyFields} label="Create policy version" onSubmit={async (v) => { const rules = v.code ? [{ code: v.code, leftEntitlementId: v.leftEntitlementId, rightEntitlementId: v.rightEntitlementId, severity: v.severity, action: v.action }] : []; await apiRequest(`${V1_ROOT}/governance/policies/access-request/versions`, { method: 'POST', idempotent: true, body: { defaultDecision: v.defaultDecision, rules, approvalPlan: approvalPlan(v) } }); }} /></details><details className="card expandable"><summary>Request Governance Exception</summary><Form fields={exceptionFields} label="Request exception" warning="Exceptions are scoped, time-bound governance evidence and never directly mutate Access." onSubmit={async (v) => { await apiRequest(`${V1_ROOT}/governance/exceptions`, { method: 'POST', idempotent: true, body: { subjectIdentityId: v.subjectIdentityId, sodRuleId: v.sodRuleId, businessReason: v.businessReason, validFrom: iso(v.validFrom), validUntil: iso(v.validUntil), predecessorExceptionId: nullable(v.predecessorExceptionId), approvalPlan: approvalPlan(v) } }); }} /></details></div>;
}

function RotationStatus() {
  const [credentialId, setCredentialId] = useState(''); const [rotationId, setRotationId] = useState(''); const [output, setOutput] = useState<Resource | null>(null);
  return <div className="card"><div className="form-grid"><label><span>Credential ID</span><input value={credentialId} onChange={(e) => setCredentialId(e.target.value)} /></label><label><span>Rotation ID</span><input value={rotationId} onChange={(e) => setRotationId(e.target.value)} /></label></div><div className="action-row"><button className="button secondary" disabled={!credentialId} onClick={() => void apiRequest<{items:Resource[]}>(withCursor(`${V1_ROOT}/credentials/${encodeURIComponent(credentialId)}/rotations`, null)).then(({data}) => setOutput({ items: data.items }))}>List rotations</button><button className="button secondary" disabled={!rotationId} onClick={() => void apiRequest<Resource>(`${V1_ROOT}/credential-rotations/${encodeURIComponent(rotationId)}`).then(({data}) => setOutput(data))}>Read rotation</button></div>{output ? <pre className="safe-json">{JSON.stringify(output, null, 2)}</pre> : null}</div>;
}

function EntitlementMapping() {
  const [mappingId, setMappingId] = useState(''); const [detail, setDetail] = useState<Resource | null>(null);
  const fields: Field[] = [{ name: 'bindingId', label: 'Connector Binding ID', required: true }, { name: 'providerStableId', label: 'Provider stable ID', required: true }, { name: 'entitlementId', label: 'Governed Entitlement ID', required: true }];
  return <div className="card"><Form fields={fields} label="Create mapping" onSubmit={async (v) => { const { data } = await apiRequest<Resource>(`${V1_ROOT}/connector-bindings/${encodeURIComponent(v.bindingId)}/entitlement-mappings`, { method: 'POST', idempotent: true, body: { providerStableId: v.providerStableId, entitlementId: v.entitlementId } }); setDetail(data); setMappingId(String(data.id ?? '')); }} /><div className="inline-form"><input placeholder="Mapping ID" value={mappingId} onChange={(e) => setMappingId(e.target.value)} /><button className="button secondary" onClick={() => void apiRequest<Resource>(`${V1_ROOT}/entitlement-observation-mappings/${encodeURIComponent(mappingId)}`).then(({data}) => setDetail(data))}>Lookup</button><button className="button danger" disabled={!mappingId} onClick={() => { if (window.confirm('Unmap this provider observation from governed Entitlement authority?')) void apiRequest(`${V1_ROOT}/entitlement-observation-mappings/${encodeURIComponent(mappingId)}:unmap`, { method: 'POST', idempotent: true }); }}>Unmap</button></div>{detail ? <pre className="safe-json">{JSON.stringify(detail, null, 2)}</pre> : null}</div>;
}

function AdministrationCreates() {
  const delegation: Field[] = [{ name: 'delegateIdentityId', label: 'Delegate Identity ID', required: true }, { name: 'sourceGrantId', label: 'Source direct Grant ID', required: true }, ...scopeFields, { name: 'validFrom', label: 'Valid from', type: 'datetime-local' }, { name: 'validUntil', label: 'Valid until', type: 'datetime-local', required: true }];
  const elevation: Field[] = [{ name: 'beneficiaryIdentityId', label: 'Beneficiary Identity ID', required: true }, { name: 'roleId', label: 'Administrative Role ID', required: true }, ...scopeFields, { name: 'validFrom', label: 'Valid from', type: 'datetime-local' }, { name: 'validUntil', label: 'Valid until', type: 'datetime-local', required: true }, { name: 'authorityBasisGrantId', label: 'Authority basis Grant ID', required: true }];
  const breakglass: Field[] = [{ name: 'roleId', label: 'Emergency Administrative Role ID', required: true }, ...scopeFields, { name: 'validUntil', label: 'Valid until', type: 'datetime-local', required: true }, { name: 'reason', label: 'Emergency reason', type: 'textarea', required: true }, { name: 'incidentReference', label: 'Incident/reference', required: true }];
  return <div className="card-grid"><details className="card expandable"><summary>Create delegation</summary><Form fields={delegation} label="Create delegation" onSubmit={async (v) => { await apiRequest(`${V1_ROOT}/administrative-delegations`, { method: 'POST', idempotent: true, body: { delegateIdentityId: v.delegateIdentityId, sourceGrantId: v.sourceGrantId, scope: scope(v), validFrom: iso(v.validFrom), validUntil: iso(v.validUntil) } }); }} /></details><details className="card expandable"><summary>Create elevation</summary><Form fields={elevation} label="Create elevation" onSubmit={async (v) => { await apiRequest(`${V1_ROOT}/administrative-elevations`, { method: 'POST', idempotent: true, body: { beneficiaryIdentityId: v.beneficiaryIdentityId, roleId: v.roleId, scope: scope(v), validFrom: iso(v.validFrom), validUntil: iso(v.validUntil), authorityBasisGrantId: v.authorityBasisGrantId } }); }} /></details><details className="card expandable"><summary>Activate break-glass</summary><Form fields={breakglass} label="Activate emergency authority" warning="Break-glass requires current STRONG assurance and a configured fail-closed policy. The server enforces those conditions and records notification/review obligations." onSubmit={async (v) => { await apiRequest(`${V1_ROOT}/administrative-break-glass-operations`, { method: 'POST', idempotent: true, body: { roleId: v.roleId, scope: scope(v), validUntil: iso(v.validUntil), reason: v.reason, incidentReference: v.incidentReference } }); }} /></details></div>;
}

const selectionFields: Field[] = [{ name: 'occurredFrom', label: 'Occurred from', type: 'datetime-local', required: true }, { name: 'occurredUntil', label: 'Occurred until', type: 'datetime-local', required: true }, { name: 'actorId', label: 'Actor ID' }, { name: 'actionType', label: 'Action type' }, { name: 'resourceType', label: 'Resource type' }, { name: 'resourceId', label: 'Resource ID' }, { name: 'outcome', label: 'Outcome', type: 'select', options: ['SUCCESS','DENIED','FAILURE'] }, { name: 'correlationId', label: 'Correlation ID' }];
const selection = (v: Values) => ({ occurredFrom: iso(v.occurredFrom), occurredUntil: iso(v.occurredUntil), actorId: nullable(v.actorId), actionType: nullable(v.actionType), resourceType: nullable(v.resourceType), resourceId: nullable(v.resourceId), outcome: nullable(v.outcome), correlationId: nullable(v.correlationId) });

function AuditOperations() {
  const [filters, setFilters] = useState<Values>({}); const [records, setRecords] = useState<Resource[]>([]); const [exportId, setExportId] = useState('');
  async function search() { const query: Record<string,string|undefined> = {}; for (const key of ['actorId','actionType','resourceType','resourceId','outcome','correlationId']) if (filters[key]) query[key] = filters[key]; const { data } = await apiRequest<{items:Resource[]}>(withCursor(`${V1_ROOT}/audit-records`, null, query)); setRecords(data.items); }
  return <><details className="card expandable"><summary>Exact AuditRecord filters</summary><div className="form-grid">{selectionFields.filter((f) => !['occurredFrom','occurredUntil'].includes(f.name)).map((field) => <label key={field.name}><span>{field.label}</span><input value={filters[field.name] ?? ''} onChange={(e) => setFilters((v) => ({ ...v, [field.name]: e.target.value }))} /></label>)}</div><button className="button secondary" onClick={() => void search()}>Search</button>{records.length ? <pre className="safe-json">{JSON.stringify(records, null, 2)}</pre> : null}</details><div className="card-grid"><details className="card expandable"><summary>Create durable export</summary><Form fields={selectionFields} label="Request export" onSubmit={async (v) => { const { data } = await apiRequest<Resource>(`${V1_ROOT}/audit-exports`, { method: 'POST', idempotent: true, body: selection(v) }); setExportId(String(data.id ?? '')); }} />{exportId ? <button className="button secondary" onClick={() => void apiDownload(`${V1_ROOT}/audit-exports/${encodeURIComponent(exportId)}:download`, { method: 'POST' }).then((blob) => { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `wyrmgate-audit-export-${exportId}.ndjson`; a.click(); URL.revokeObjectURL(url); })}>Download completed export</button> : null}</details><details className="card expandable"><summary>Create legal hold</summary><Form fields={[...selectionFields,{name:'reasonCode',label:'Reason code',required:true},{name:'caseReference',label:'Case reference',required:true}]} label="Create legal hold" onSubmit={async (v) => { await apiRequest(`${V1_ROOT}/audit-evidence-lifecycle/legal-holds`, { method: 'POST', idempotent: true, body: { selection: selection(v), reasonCode: v.reasonCode, caseReference: v.caseReference } }); }} /></details><details className="card expandable"><summary>Request destructive purge</summary><Form fields={[{name:'archiveSegmentId',label:'Verified archive segment ID',required:true},...selectionFields,{name:'reasonCode',label:'Reason code',required:true}]} label="Request purge" warning="Destructive Audit purge is dual-control and server-fenced by archive evidence, retention and legal-hold checks." onSubmit={async (v) => { await apiRequest(`${V1_ROOT}/audit-evidence-lifecycle/purges`, { method: 'POST', idempotent: true, body: { archiveSegmentId: v.archiveSegmentId, selection: selection(v), reasonCode: v.reasonCode } }); }} /></details></div></>;
}

export function AccessPage() { return <><BaseAccessPage /><Supplement title="Lifecycle policy activation" description="Typed accepted policy predicates and targets; no generic expression editor."><LifecyclePolicyActivation /></Supplement></>; }
export function PoliciesPage() { return <><BasePoliciesPage /><Supplement title="Governance policy and exception creation" description="Accepted ACCESS_REQUEST PolicyVersion and scoped GovernanceException creation workflows."><GovernanceCreates /></Supplement></>; }
export function CredentialsPage() { return <><BaseCredentialsPage /><Supplement title="Credential rotation status" description="Durable CredentialRotation is process state, separate from Credential authoritative lifecycle."><RotationStatus /></Supplement></>; }
export function IntegrationsPage() { return <><BaseIntegrationsPage /><Supplement title="Provider observation mapping" description="Explicit provider observation to governed Entitlement mapping; mapping does not create Catalog or Access authority."><EntitlementMapping /></Supplement></>; }
export function AdministrationPage() { return <><BaseAdministrationPage /><Supplement title="Delegated, elevated and emergency authority creation" description="Typed Administration-owned authority workflows; server-side ceilings and assurance checks remain final."><AdministrationCreates /></Supplement></>; }
export function AuditPage() { return <><BaseAuditPage /><Supplement title="Audit search, export and evidence lifecycle" description="Exact bounded filters plus durable export/legal-hold/purge operations."><AuditOperations /></Supplement></>; }
